### ISSUE TITLE
Can't install new version on windows 10

### ISSUE THREAD

**Issue by a-elkaim** [FallingSnow/h265ize-gui#13]
I have the following error :

npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

**Comment by FallingSnow** [comment]
@azsde sorry I didn't even get an email about this new issue. That is just a warning, in this case fsevents is an optional library for Mac that provides better access the file system events. On Windows and Linux a different means is used.

Is it actually not installing, because then you might have an error else where.

**Comment by a-elkaim** [comment]
You are right, it is installing correctly
